import { pgTable, integer, varchar, timestamp, doublePrecision } from "drizzle-orm/pg-core";

export const tgfparTable = pgTable("tgfpar", {
  codparc: integer("codparc").primaryKey(),
  codvend: integer("codvend"),
  nomeparc: varchar("nomeparc", { length: 40 }),
  razaosocial: varchar("razaosocial", { length: 40 }),
  tippessoa: varchar("tippessoa", { length: 1 }),
  codparcmatriz: integer("codparcmatriz"),
  codend: integer("codend"),
  numend: varchar("numend", { length: 6 }),
  complemento: varchar("complemento", { length: 30 }),
  codbai: integer("codbai"),
  codcid: integer("codcid"),
  codreg: integer("codreg"),
  cep: varchar("cep", { length: 8 }),
  telefone: varchar("telefone", { length: 20 }),
  fax: varchar("fax", { length: 20 }),
  email: varchar("email", { length: 80 }),
  dtcad: timestamp("dtcad"),
  dtalter: timestamp("dtalter"),
  identinscestad: varchar("identinscestad", { length: 16 }),
  cgc_cpf: varchar("cgc_cpf", { length: 14 }),
  cliente: varchar("cliente", { length: 1 }),
  fornecedor: varchar("fornecedor", { length: 1 }),
  transportadora: varchar("transportadora", { length: 1 }),
  vendedor: varchar("vendedor", { length: 1 }),
  agencia: varchar("agencia", { length: 1 }),
  codtipparc: integer("codtipparc"),
  codbco: integer("codbco"),
  tare: varchar("tare", { length: 1 }),
  ipiincicms: varchar("ipiincicms", { length: 1 }),
  retemiss: varchar("retemiss", { length: 1 }),
  reteminss: varchar("reteminss", { length: 1 }),
  ativo: varchar("ativo", { length: 1 }),
  bloquear: varchar("bloquear", { length: 1 }),
  ctaadiant: varchar("ctaadiant", { length: 1 }),
  codassessor: integer("codassessor"),
  calcinss: varchar("calcinss", { length: 1 }),
  codusu: integer("codusu"),
  retempis: varchar("retempis", { length: 1 }),
  retemcofins: varchar("retemcofins", { length: 1 }),
  retemcsl: varchar("retemcsl", { length: 1 }),
  usuario: varchar("usuario", { length: 1 }),
  temipi: varchar("temipi", { length: 1 }),
  aluno: varchar("aluno", { length: 1 }),
  professor: varchar("professor", { length: 1 }),
  descbonif: varchar("descbnif", { length: 1 }),
  implaudolote: varchar("implaudolote", { length: 1 }),
  medico: varchar("medico", { length: 1 }),
  tipofatur: varchar("tipofatur", { length: 1 }),
  motorista: varchar("motorista", { length: 1 }),
  operlogist: varchar("operlogist", { length: 1 }),
  agronomo: varchar("agronomo", { length: 1 }),
  produtortemnf: varchar("produtortemnf", { length: 1 }),
  flex: varchar("flex", { length: 1 }),
  simples: varchar("simples", { length: 1 }),
  tipanexonfe: varchar("tipanexonfe", { length: 1 }),
  codusucobr: integer("codusucobr"),
  emaildanfe: varchar("emaildanfe", { length: 1 }),
  permitecorte: varchar("permitecorte", { length: 1 }),
  statusedz: varchar("statusedz", { length: 1 }),
  sitreceita: varchar("sitreceita", { length: 1 }),
  sitsintegra: varchar("sitsintegra", { length: 1 }),
  sitccf: varchar("sitccf", { length: 1 }),
  usatabcrforn: varchar("usatabcrforn", { length: 1 }),
  artprecad: varchar("artprecad", { length: 1 }),
  gerctrcauto: varchar("gerctrcauto", { length: 1 }),
  codlocalpadrao: integer("codlocalpadrao"),
  entregaendcontato: varchar("entregaendcontato", { length: 1 }),
  retstvenda: varchar("retstvenda", { length: 1 }),
  tipogerboleto: varchar("tipogerboleto", { length: 1 }),
  tipogerboletodup: varchar("tipogerboletodup", { length: 1 }),
  boldestemail: varchar("boldestemail", { length: 1 }),
  aplicleitransp: varchar("aplicleitransp", { length: 1 }),
  integraeconect: varchar("integraeconect", { length: 1 }),
  baseprazoeconect: integer("baseprazoeconect"),
  baseparceleconect: integer("baseparceleconect"),
  perfileconect: varchar("perfileconect", { length: 1 }),
  envipedemailtop: varchar("envipedemailtop", { length: 1 }),
  emailnfe: varchar("emailnfe", { length: 255 }),
});

export type Tgfpar = typeof tgfparTable.$inferSelect;