import { pgTable, integer, varchar, timestamp, doublePrecision } from "drizzle-orm/pg-core";

export const tgfproTable = pgTable("tgfpro", {
  codprod: integer("codprod").primaryKey(),
  descrprod: varchar("descrprod", { length: 120 }),
  referencia: varchar("referencia", { length: 15 }),
  codgrupoprod: integer("codgrupoprod"),
  codvol: varchar("codvol", { length: 2 }),
  codvolcompra: varchar("codvolcompra", { length: 2 }),
  pesobruto: doublePrecision("pesobruto"),
  pesoliq: doublePrecision("pesoliq"),
  alertaestmin: varchar("alertaestmin", { length: 1 }),
  promocao: varchar("promocao", { length: 1 }),
  temicms: varchar("temicms", { length: 1 }),
  temiss: varchar("temiss", { length: 1 }),
  temipivenda: varchar("temipivenda", { length: 1 }),
  temipicompra: varchar("temipicompra", { length: 1 }),
  temirf: varchar("temirf", { length: 1 }),
  teminss: varchar("teminss", { length: 1 }),
  percinss: doublePrecision("percinss"),
  redbaseinss: doublePrecision("redbaseinss"),
  ativo: varchar("ativo", { length: 1 }),
  estmax: doublePrecision("estmax"),
  estmin: doublePrecision("estmin"),
  apresdetalhe: varchar("apresdetalhe", { length: 1 }),
  codmoeda: integer("codmoeda"),
  dtalter: timestamp("dtalter"),
  codusu: integer("codusu"),
  hrdobrada: varchar("hrdobrada", { length: 1 }),
  icmsgerencia: varchar("icmsgerencia", { length: 1 }),
  codnat: integer("codnat"),
  codcencus: integer("codcencus"),
  codproj: integer("codproj"),
  temciap: varchar("temciap", { length: 1 }),
  implaudolote: varchar("implaudolote", { length: 1 }),
  dimensoes: varchar("dimensoes", { length: 1 }),
  padrao: varchar("padrao", { length: 1 }),
  solcompra: varchar("solcompra", { length: 1 }),
  confere: varchar("confere", { length: 1 }),
  remeter: varchar("remeter", { length: 1 }),
  temcomissao: varchar("temcomissao", { length: 1 }),
  ap1rctego: varchar("ap1rctego", { length: 1 }),
  calculogiro: varchar("calculogiro", { length: 1 }),
  confcegapeso: varchar("confcegapeso", { length: 1 }),
  regrawms: varchar("regrawms", { length: 1 }),
  grupopis: varchar("grupopis", { length: 30 }),
  grupocofins: varchar("grupocofins", { length: 30 }),
  grupocssl: varchar("grupocssl", { length: 30 }),
  utilizawms: varchar("utilizawms", { length: 1 }),
  balanca: varchar("balanca", { length: 1 }),
  geraplaprod: varchar("geraplaprod", { length: 1 }),
  produtonfe: integer("produtonfe"),
  tipgtinnfe: integer("tipgtinnfe"),
  flex: varchar("flex", { length: 1 }),
  imprimir: varchar("imprimir", { length: 1 }),
  confirmaimp: varchar("confirmaimp", { length: 1 }),
  qtdnflaudosint: integer("qtdnflaudosint"),
  tipcontestwms: varchar("tipcontestwms", { length: 1 }),
  listalpm: varchar("listalpm", { length: 1 }),
  oneroso: varchar("oneroso", { length: 1 }),
  refmercmed: varchar("refmercmed", { length: 1 }),
  termolabil: varchar("termolabil", { length: 1 }),
  controlado: varchar("controlado", { length: 1 }),
  idencorrelato: varchar("idencorrelato", { length: 1 }),
  idencosme: varchar("idencosme", { length: 1 }),
  prodfalta: varchar("prodfalta", { length: 1 }),
  statusmed: integer("statusmed"),
  mvaajustado: doublePrecision("mvaajustado"),
  infpureza: varchar("infpureza", { length: 1 }),
  usastatuslote: varchar("usastatuslote", { length: 1 }),
  origemfat: varchar("origemfat", { length: 1 }),
  usacodbarrasqtd: varchar("usacodbarrasqtd", { length: 1 }),
  valcapm3: varchar("valcapm3", { length: 1 }),
  qtdpecafrac: varchar("qtdpecafrac", { length: 1 }),
  utilordcorte: varchar("utilordcorte", { length: 1 }),
  impordemcorte: varchar("impordemcorte", { length: 1 }),
  perctroca: doublePrecision("perctroca"),
  temcredpiscofinsdepr: varchar("temcredpiscofinsdepr", { length: 1 }),
  utilsmartcard: varchar("utilsmartcard", { length: 1 }),
  recupavaria: varchar("recupavaria", { length: 1 }),
  apresform: varchar("apresform", { length: 1 }),
  codbarcomp: varchar("codbarcomp", { length: 1 }),
  temmedicao: varchar("temmedicao", { length: 1 }),
  natbcpiscofins: varchar("natbcpiscofins", { length: 1 }),
  contarporpeso: varchar("contarporpeso", { length: 1 }),
  permcompprod: varchar("permcompprod", { length: 1 }),
  codexncm: integer("codexncm"),
  qtdcst: integer("qtdcst"),
  diascst: integer("diascst"),
  perctolvarcst: integer("perctolvarcst"),
  valcbglobal: varchar("valcbglobal", { length: 1 }),
  usapontos: varchar("usapontos", { length: 1 }),
  integraeconect: varchar("integraeconect", { length: 1 }),
  dtvaldif: varchar("dtvaldif", { length: 1 }),
  enqreintegra: varchar("enqreintegra", { length: 1 }),
  codbarbalanca: varchar("codbarbalanca", { length: 1 }),
  perccmtnac: doublePrecision("perccmtnac"),
  perccmtimp: doublePrecision("perccmtimp"),
  produzaut: varchar("produzaut", { length: 1 }),
  usaimpagrupmin: varchar("usaimpagrupmin", { length: 1 }),
  rastrestoque: varchar("rastrestoque", { length: 1 }),
  impetiqconf: varchar("impetiqconf", { length: 1 }),
  servparaindust: varchar("servparaindust", { length: 1 }),
  cat1799spres: varchar("cat1799spres", { length: 1 }),
  geracustcompseg: varchar("geracustcompseg", { length: 1 }),
  estsegqtd: doublePrecision("estsegqtd"),
  estmaxqtd: doublePrecision("estmaxqtd"),
  desviomax: doublePrecision("desviomax"),
  arredagrup: doublePrecision("arredagrup"),
  aplicasazo: varchar("aplicasazo", { length: 1 }),
  lotecompminimo: doublePrecision("lotecompminimo"),
  agrupcompminimo: doublePrecision("agrupcompminimo"),
  usaseriesepwms: varchar("usaseriesepwms", { length: 1 }),
  fixoagenda: varchar("fixoagenda", { length: 1 }),
  exibcompexpkit: varchar("exibcompexpkit", { length: 1 }),
  calcdifal: varchar("calcdifal", { length: 1 }),
  temrastrolote: varchar("temrastrolote", { length: 1 }),
  tipocontagem: varchar("tipocontagem", { length: 1 }),
  perccmtfed: doublePrecision("perccmtfed"),
  perccmtest: doublePrecision("perccmtest"),
  perccmtmun: doublePrecision("perccmtmun"),
});

export type Tgfpro = typeof tgfproTable.$inferSelect;